image: java:8-jdk

before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - ./gradlew check

build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - ./sqool-erp-service/build/libs/sqool-erp-service-1.1.0.jar
    expire_in: 1 day
  only:
    - master

deploy:
  image: ubuntu:18.04
  stage: deploy
  script:
    - apt-get update -y && apt-get install -y openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - scp -r sqool-erp-service-1.1.0.jar ubuntu@212.64.60.130:/home/ubuntu/sqool/sqool-service/
    - ssh ubuntu@212.64.60.130
    - cd /home/ubuntu/sqool/sqool-service/
#    - ./restart_server.sh
    - ll
  only:
    - master


