image: java:8-jdk

stages:
  - test
  - build

test:
  stage: test
  script:
    - ./gradlew check

build:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day
  only:
    - master
