package com.abuqool.sqool.auth;

public enum MgmtGraphQLOps {
    QUERY_ALL_SCHOOLS,
    QUERY_SCHOOL,
    MUTATION_SAVE_SCHOOL,
    MUTATION_DELETE_SCHOOL,
    MUTATION_DISABLE_SCHOOL,

    QUERY_PRODUCT,
    QUERY_PRODUCTS,
    MUTATION_DISABLE_PRODUCT,
    MUTATION_SAVE_PRODUCT,
    MUTATION_PUSH_PRODUCT_TO_SCHOOL,

    QUERY_WHOAMI,
    MUTATION_SAVE_EVENT, MUTATION_ENABLE_LISTING, MUTATION_DISABLE_LISTING, QUERY_LISTING, MUTATION_SAVE_OPERATOR, MUTATION_GEN_SCHOOL_QR, MUTATION_SAVE_SCHOOL_CLZ, MUTATION_SET_LISTING,

}
